### ISSUE TITLE
`DataStateUseCase` and local data

### ISSUE THREAD

**Issue by mainrs** [developersancho/RortyCompose.V2#1]
I was adapting the way you layed out your domain layer into one of my apps. I wanted to ask if [DataStateUseCase](https://github.com/developersancho/RortyCompose.V2/blob/005bc74f4affab957ec8b671d56af26da4a8e737/libraries/framework/src/main/java/com/developersancho/framework/usecase/DataStateUseCase.kt#L9) is meant to be used for remote data only since it can't be observed when the underlying data changes.

I used it for retrieving local data from Room. The problem I encountered was when the data in Room changed. The returned data from my usecase did not update properly since I could not return a `Flow`. At the end I moved to `ReturnUseCase`. I originally used `DataStateUseCase` since querying the data did have a noticable delay and I wanted to show a proper loading UI element if the data is still being queried.

**Comment by developersancho** [comment]
[DataStateUseCase](https://github.com/developersancho/RortyCompose.V2/blob/005bc74f4affab957ec8b671d56af26da4a8e737/libraries/framework/src/main/java/com/developersancho/framework/usecase/DataStateUseCase.kt#L9) not using for observing data. It just for handle with [DataState](https://github.com/developersancho/RortyCompose.V2/blob/005bc74f4affab957ec8b671d56af26da4a8e737/libraries/framework/src/main/java/com/developersancho/framework/network/DataState.kt).

If you want to observe your data you can review here [observers package](https://github.com/chrisbanes/tivi/tree/main/domain/src/main/java/app/tivi/domain/observers) and use this [SubjectInteractor](https://github.com/chrisbanes/tivi/blob/main/domain/src/main/java/app/tivi/domain/Interactor.kt)

Maybe it will be helpful. I could not try.

**Comment by developersancho** [comment]
It is closed
